<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AnalysisMode>All</AnalysisMode>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>

    <!-- <RootNamespace></RootNamespace> -->

    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAudit>true</NuGetAudit>
  </PropertyGroup>
</Project>